// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfaopncdcgmkpdwaqgjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYW9wbmNkY2dta3Bkd2FxZ2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzgxNTYsImV4cCI6MjA2NTE1NDE1Nn0.69O2xq-OaRF1f6d4Qd-NI3hOVl-o1fjAMPZDCgHWnqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);