// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// @ts-ignore
const SUPABASE_URL = __SUPABASE_URL__;
// @ts-ignore
const SUPABASE_ANON_KEY = __SUPABASE_ANON_KEY__;

console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Anon Key length:', SUPABASE_ANON_KEY?.length);

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);